### PR TITLE
Tutorial review learning

### PR DESCRIPTION
**Pull request by moschmdt**
Reviewed the tutorials 5, 6, 7 and 8 - they should be in line with the word/pdf version.

I removed the WIP warning for those tutorials. Should we link to the old PDFs nonetheless?

The manual chapter has just some linting adjustments.

### CODE REVIEW

**Comment by garfieldnate** [comment]
Thank you for working on this!

* It looks like 5 still has a bunch of linting warnings that failed the build. Not sure if those prevent the site from building after merging.
* Yes, I would like to provide the PDF versions as a courtesy to those that want them. Longer-term, I'd like to generate the PDFs from this markdown source so that we don't have two versions floating around. The tutorials aren't modified much, so it's not as big an issue as it is with the manual.

**Comment by moschmdt** [comment]
I just added the [admonitions](https://squidfunk.github.io/mkdocs-material/reference/admonitions/) plugin with some suggested default configuration to get rid of the HTML footnotes in the Markdown.

**Comment by moschmdt** [comment]
I just downloaded an example page as PDF via the print dialogue of the browser and it actually looks very reasonable and the links are also working "out-of-the-box".
[Semantic Memory - Soar Home.pdf](https://github.com/user-attachments/files/16470480/Semantic.Memory.-.Soar.Home.pdf)

**Comment by garfieldnate** [comment]
That PDF *does* look great! I didn't realize mkdocs had such good print styling, but I suppose it makes sense.

The PDFs are distributed with Soar, so I would want to figure out a way to generate them automatically. Headless chrome or selenium or something. I tried `wkhtmltopdf`, but it ignored all styling and the output looked awful, so that possibility is eliminated. I think this is a good path, though.

I like the look of the admonitions, as well.

Part of the reason I marked all of these pages as "under construction" was because the images are not usable when the site is in dark mode. They either need a light background or to be reworked to update automatically for dark mode (the latter is a bit of a production).

**Comment by garfieldnate** [comment]
`rl-optrace.svg` appears to be an invalid SVG (at least according to GitHub).

Yes, I would leave the admonition in for now; you can change it to be more specific about dark mode being an issue, if you like.

**Comment by moschmdt** [comment]
Do you know if there is a new command for `watch --chunks --print`? (Tutorial V: Planning and learning) I get the following error message in the debugger:

```shell
no such option: print
```

**Comment by garfieldnate** [comment]
When I put in `watch --chunks` I get `Now printing when chunks fire.`, so maybe you just need to remove the `--print`.

GitHub still says that SVG file is malformed.

**Comment by moschmdt** [comment]
Interesting... Do you see some kind of error message since I don't get any warning? I just checked the local version in both light and dark mode. It appears to be fine for mkdocs.

**Comment by garfieldnate** [comment]
Actually I think the image is fine :D It shows an error in the commits view, but shows properly in the "Files Changed" view.

Is this ready merge?

**Comment by moschmdt** [comment]
> Is this ready merge?

Yes!

**Comment by garfieldnate** [comment]
Great, thanks for the all work!

**Pull request merged**
